extern void uart0_init(unsigned int baud);
extern void uart0_tx(unsigned char data);
extern unsigned char uart0_rx(void);
extern void delay_ms(unsigned int ms);
extern void delay_sec(unsigned int sec);
extern void uart0_binary(int num);
extern void uart0_string(char *p);
extern void lcd_data(unsigned char data);
extern void lcd_cmd(unsigned int cmd);
extern void lcd_init(void);
extern void lcd_string(char *p);
extern void lcd_integer(int num);
extern void lcd_cgram(void);
extern void uart0_int(int num);
